version: "3.10"

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile-backend
    environment:
      DATABASE_URI: sqlite:////srv/data/db.sqlite
    volumes:
      - db_data:/srv/data

  # The `proxy` service could serve the static HTML content,
  #  but set in a different service so we can update only this service without modifying `proxy`
  # (Also we could later use some SSR)
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile-frontend
    volumes:
      - ./docker/nginx-frontend.conf:/etc/nginx/conf.d/default.conf:ro

  # Proxy to the services
  proxy:
    image: nginx:1.25-alpine
    depends_on:
      - backend
      - frontend
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db_data:
